// known-paths.js — ICD-10 & ICD-9-CM Vol.3 Index Paths
// Auto-generated — edit here, bukan di index.html
// Total: 271 entries

const KNOWN_PATHS = {
'O36.4': 'Death\n- fetus, fetal\n-- (near term) O36.4\nO36.4 Maternal care for intrauterine death',
    'O43.0': 'Syndrome\n- transfusion\n-- feto-fetal O43.0\nO43.0 Placental transfusion syndromes',
    'O30.0': 'Pregnancy\n- complicated by\n-- multiple gestation\n--- twin O30.0\nO30.0 Twin pregnancy',
    'O60.1': 'Labour\n- premature\n-- with delivery O60.1\nO60.1 Preterm labour with preterm delivery',
    'O60.0': 'Labour\n- premature O60.0\nO60.0 Preterm labour without delivery',
    'O34.2': 'Section\n- cesarean (for)\n-- previous\n--- cesarean section O34.2\nO34.2 Maternal care due to uterine scar from previous surgery',
    'O03.5': 'Abortion\n- spontaneous\n-- complicated by\n--- genital tract and pelvic infection O03.5\nO03.5 Spontaneous abortion, complete, complicated by genital tract and pelvic infection',
    'O03.0': 'Abortion\n- spontaneous\n-- complicated by\n--- genital tract and pelvic infection O03.0\nO03.0 Spontaneous abortion, incomplete, complicated by genital tract and pelvic infection',
    'O03.9': 'Abortion\n- spontaneous\n-- unspecified O03.9\nO03.9 Spontaneous abortion, unspecified',
    'O03.4': 'Abortion\n- spontaneous\n-- incomplete, without complication O03.4\nO03.4 Spontaneous abortion, incomplete, without complication',
    'O08.0': 'Complications\n- following\n-- abortion and ectopic and molar pregnancy\n--- infection O08.0\nO08.0 Genital tract and pelvic infection following abortion and ectopic and molar pregnancy',
    'O00.1': 'Pregnancy\n- ectopic\n-- tubal\n--- ruptured O00.1\nO00.1 Tubal pregnancy',
    'Z37.3': 'Outcome of delivery\n- twins\n-- one liveborn one stillborn Z37.3\nZ37.3 Twins, one liveborn and one stillborn',
    'Z37.0': 'Outcome of delivery\n- single\n-- liveborn Z37.0\nZ37.0 Single liveborn infant',
    'N83.2': 'Cyst\n- ovary, ovarian N83.2\nN83.2 Other and unspecified ovarian cysts',
    'S72.3': 'Fracture\n- femur\n-- shaft S72.3\nS72.3 Fracture of shaft of femur',
    'S72.0': 'Fracture\n- femur\n-- neck S72.0\nS72.0 Fracture of neck of femur',
    'S72.1': 'Fracture\n- femur\n-- pertrochanteric S72.1\nS72.1 Pertrochanteric fracture',
    'S72.9': 'Fracture\n- femur S72.9\nS72.9 Fracture of femur, unspecified',
    '79.05': 'Reduction\n- fracture\n-- femur\n--- closed 79.05\n79.05 Closed reduction of fracture without internal fixation, femur',
    '79.15': 'Reduction\n- fracture\n-- femur\n--- open\n---- with internal fixation 79.15\n79.15 Open reduction of fracture with internal fixation, femur',
    '79.35': 'Nailing\n- intramedullary\n-- femur 79.35\n79.35 Open reduction of fracture with internal fixation, femur',
    '79.36': 'Nailing\n- intramedullary\n-- tibia 79.36\n79.36 Open reduction of fracture with internal fixation, tibia and fibula',
    '00.66': 'Angioplasty\n- coronary (balloon) 00.66\n00.66 Percutaneous transluminal coronary angioplasty',
    '36.06': 'Insertion\n- stent\n-- coronary artery 36.06\n36.06 Insertion of coronary artery stent',
    '36.01': 'Bypass\n- coronary artery 36.01\n36.01 Single coronary artery bypass using saphenous vein graft',
    '14.24': 'Photocoagulation\n- retina\n-- for\n--- destruction of lesion\n---- laser 14.24\n14.24 Destruction of chorioretinal lesion by laser photocoagulation',
    '14.25': 'Photocoagulation\n- retina\n-- for\n--- destruction of lesion\n---- unspecified type 14.25\n14.25 Destruction of chorioretinal lesion by photocoagulation of unspecified type',
    '14.23': 'Photocoagulation\n- retina\n-- for\n--- destruction of lesion\n---- xenon arc 14.23\n14.23 Destruction of chorioretinal lesion by xenon arc photocoagulation',
    '14.26': 'Photocoagulation\n- retina\n-- for\n--- destruction of lesion\n---- cryotherapy 14.26\n14.26 Destruction of chorioretinal lesion by cryotherapy',
    '16.49': 'Enucleation\n- eyeball 16.49\n16.49 Enucleation of eyeball',
    '08.36': 'Repair\n- eyelid\n-- blepharoplasty 08.36\n08.36 Eyelid reconstruction',
    'I50.0': 'Failure\n- heart\n-- congestive I50.0\nI50.0 Congestive heart failure',
    'I50.1': 'Failure\n- heart\n-- left I50.1\nI50.1 Left ventricular failure',
    'I50.9': 'Failure\n- heart\n-- unspecified I50.9\nI50.9 Heart failure, unspecified',
    'I48': 'Fibrillation\n- atrial I48\nI48 Atrial fibrillation and flutter',
    'I47.1': 'Tachycardia\n- ventricular I47.1\nI47.1 Supraventricular tachycardia',
    'I47.2': 'Tachycardia\n- ventricular I47.2\nI47.2 Ventricular tachycardia',
    'I49.0': 'Fibrillation\n- ventricular I49.0\nI49.0 Ventricular fibrillation and flutter',
    'I11.0': 'Hypertension\n- heart disease\n-- with heart failure I11.0\nI11.0 Hypertensive heart disease with heart failure',
    'I11.9': 'Hypertension\n- heart disease\n-- without heart failure I11.9\nI11.9 Hypertensive heart disease without heart failure',
    'I13.1': 'Hypertension\n- cardiorenal disease\n-- with renal failure I13.1\nI13.1 Hypertensive heart and renal disease with renal failure',
    'I20.0': 'Angina\n- unstable I20.0\nI20.0 Unstable angina',
    'I20.9': 'Angina\n- pectoris\n-- unspecified I20.9\nI20.9 Angina pectoris, unspecified',
    'I21.2': 'Infarction\n- myocardial\n-- acute\n--- lateral I21.2\nI21.2 Acute transmural myocardial infarction of lateral wall',
    'I21.3': 'Infarction\n- myocardial\n-- acute\n--- unspecified site I21.3\nI21.3 Acute transmural myocardial infarction of unspecified site',
    'I25.1': 'Disease\n- coronary\n-- artery\n--- atherosclerotic heart disease I25.1\nI25.1 Atherosclerotic heart disease',
    'I25.2': 'Infarction\n- myocardial\n-- old I25.2\nI25.2 Old myocardial infarction',
    'I26.9': 'Embolism\n- pulmonary\n-- without mention of acute cor pulmonale I26.9\nI26.9 Pulmonary embolism without mention of acute cor pulmonale',
    'I27.0': 'Hypertension\n- pulmonary\n-- primary I27.0\nI27.0 Primary pulmonary hypertension',
    'I35.0': 'Stenosis\n- aortic valve I35.0\nI35.0 Aortic stenosis',
    'I34.0': 'Regurgitation\n- mitral valve I34.0\nI34.0 Mitral valve regurgitation',
    'R57.0': 'Shock\n- cardiogenic R57.0\nR57.0 Cardiogenic shock',
    'J45.0': 'Asthma\n- predominantly allergic J45.0\nJ45.0 Predominantly allergic asthma',
    'J45.1': 'Asthma\n- nonallergic J45.1\nJ45.1 Nonallergic asthma',
    'J45.9': 'Asthma\n- unspecified J45.9\nJ45.9 Asthma, unspecified',
    'J46': 'Status\n- asthmaticus J46\nJ46 Status asthmaticus',
    'J15.7': 'Pneumonia\n- due to\n-- Mycoplasma pneumoniae J15.7\nJ15.7 Pneumonia due to Mycoplasma pneumoniae',
    'J22': 'Infection\n- respiratory\n-- lower\n--- acute J22\nJ22 Unspecified acute lower respiratory infection',
    'J90': 'Effusion\n- pleural J90\nJ90 Pleural effusion, not elsewhere classified',
    'J93.1': 'Pneumothorax\n- spontaneous J93.1\nJ93.1 Other spontaneous pneumothorax',
    'J93.9': 'Pneumothorax\n- unspecified J93.9\nJ93.9 Pneumothorax, unspecified',
    'A15.0': 'Tuberculosis\n- pulmonary\n-- confirmed by sputum smear A15.0\nA15.0 Tuberculosis of lung, confirmed by sputum smear with or without culture',
    'A15.3': 'Tuberculosis\n- pulmonary\n-- confirmed histologically A15.3\nA15.3 Tuberculosis of lung, confirmed histologically',
    'A16.2': 'Tuberculosis\n- pulmonary\n-- without mention of bacteriological or histological confirmation A16.2\nA16.2 Tuberculosis of lung, without mention of bacteriological or histological confirmation',
    'J96.9': 'Failure\n- respiratory\n-- unspecified J96.9\nJ96.9 Respiratory failure, unspecified',
    'K25.0': 'Ulcer\n- gastric\n-- acute\n--- with haemorrhage K25.0\nK25.0 Gastric ulcer, acute with haemorrhage',
    'K25.9': 'Ulcer\n- gastric\n-- unspecified K25.9\nK25.9 Gastric ulcer, unspecified',
    'K26.9': 'Ulcer\n- duodenal\n-- unspecified K26.9\nK26.9 Duodenal ulcer, unspecified',
    'K29.7': 'Gastritis\n- unspecified K29.7\nK29.7 Gastritis, unspecified',
    'K40.9': 'Hernia\n- inguinal\n-- without obstruction or gangrene K40.9\nK40.9 Unilateral or unspecified inguinal hernia, without obstruction or gangrene',
    'K40.3': 'Hernia\n- inguinal\n-- unilateral\n--- with obstruction K40.3\nK40.3 Unilateral or unspecified inguinal hernia, with obstruction, without gangrene',
    'K56.7': 'Ileus\n- unspecified K56.7\nK56.7 Ileus, unspecified',
    'K56.6': 'Obstruction\n- intestinal\n-- unspecified K56.6\nK56.6 Other and unspecified intestinal obstruction',
    'K70.3': 'Cirrhosis\n- liver\n-- alcoholic K70.3\nK70.3 Alcoholic cirrhosis of liver',
    'K74.6': 'Cirrhosis\n- liver\n-- unspecified K74.6\nK74.6 Other and unspecified cirrhosis of liver',
    'K72.0': 'Failure\n- liver\n-- acute K72.0\nK72.0 Acute and subacute hepatic failure',
    'K72.9': 'Failure\n- liver\n-- unspecified K72.9\nK72.9 Hepatic failure, unspecified',
    'B18.1': 'Hepatitis\n- B\n-- chronic B18.1\nB18.1 Chronic viral hepatitis B without delta-agent',
    'B18.2': 'Hepatitis\n- C\n-- chronic B18.2\nB18.2 Chronic viral hepatitis C',
    'K80.2': 'Calculus\n- gallbladder\n-- without cholecystitis K80.2\nK80.2 Calculus of gallbladder without cholecystitis',
    'K81.0': 'Cholecystitis\n- acute K81.0\nK81.0 Acute cholecystitis',
    'K85': 'Pancreatitis\n- acute K85\nK85 Acute pancreatitis',
    'K86.1': 'Pancreatitis\n- chronic K86.1\nK86.1 Other chronic pancreatitis',
    'I63.0': 'Infarction\n- cerebral\n-- due to thrombosis I63.0\nI63.0 Cerebral infarction due to thrombosis of precerebral arteries',
    'I63.3': 'Infarction\n- cerebral\n-- due to thrombosis of cerebral arteries I63.3\nI63.3 Cerebral infarction due to thrombosis of cerebral arteries',
    'I63.4': 'Infarction\n- cerebral\n-- due to embolism I63.4\nI63.4 Cerebral infarction due to embolism of cerebral arteries',
    'I61.0': 'Haemorrhage\n- cerebral\n-- subcortical I61.0\nI61.0 Nontraumatic intracerebral haemorrhage in hemisphere, subcortical',
    'I61.3': 'Haemorrhage\n- cerebral\n-- brain stem I61.3\nI61.3 Nontraumatic intracerebral haemorrhage in brain stem',
    'I62.9': 'Haemorrhage\n- intracranial\n-- unspecified I62.9\nI62.9 Nontraumatic intracranial haemorrhage, unspecified',
    'G40.9': 'Epilepsy\n- unspecified G40.9\nG40.9 Epilepsy, unspecified',
    'G41.0': 'Status\n- epilepticus\n-- grand mal G41.0\nG41.0 Grand mal status epilepticus',
    'G41.9': 'Status\n- epilepticus\n-- unspecified G41.9\nG41.9 Status epilepticus, unspecified',
    'G00.9': 'Meningitis\n- bacterial\n-- unspecified G00.9\nG00.9 Bacterial meningitis, unspecified',
    'G03.9': 'Meningitis\n- unspecified G03.9\nG03.9 Meningitis, unspecified',
    'G61.0': 'Syndrome\n- Guillain-Barre G61.0\nG61.0 Guillain-Barre syndrome',
    'G35': 'Sclerosis\n- multiple G35\nG35 Multiple sclerosis',
    'G43.9': 'Migraine\n- unspecified G43.9\nG43.9 Migraine, unspecified',
    'R55': 'Syncope\n- and collapse R55\nR55 Syncope and collapse',
    'N10': 'Nephritis\n- tubulo-interstitial\n-- acute N10\nN10 Acute tubulo-interstitial nephritis',
    'N11.9': 'Nephritis\n- tubulo-interstitial\n-- chronic\n--- unspecified N11.9\nN11.9 Chronic tubulo-interstitial nephritis, unspecified',
    'N17.9': 'Failure\n- renal\n-- acute\n--- unspecified N17.9\nN17.9 Acute renal failure, unspecified',
    'N18.0': 'Failure\n- renal\n-- end-stage N18.0\nN18.0 End-stage renal disease',
    'N18.9': 'Failure\n- renal\n-- chronic\n--- unspecified N18.9\nN18.9 Chronic renal failure, unspecified',
    'N19': 'Failure\n- renal\n-- unspecified N19\nN19 Unspecified renal failure',
    'N20.0': 'Calculus\n- kidney N20.0\nN20.0 Calculus of kidney',
    'N20.1': 'Calculus\n- ureter N20.1\nN20.1 Calculus of ureter',
    'N20.2': 'Calculus\n- kidney\n-- with ureter N20.2\nN20.2 Calculus of kidney with calculus of ureter',
    'N23': 'Colic\n- renal N23\nN23 Unspecified renal colic',
    'N30.0': 'Cystitis\n- acute N30.0\nN30.0 Acute cystitis',
    'N30.9': 'Cystitis\n- unspecified N30.9\nN30.9 Cystitis, unspecified',
    'N39.0': 'Infection\n- urinary tract N39.0\nN39.0 Urinary tract infection, site not specified',
    'N40': 'Hyperplasia\n- prostate N40\nN40 Hyperplasia of prostate',
    'N13.5': 'Hydronephrosis\n- with ureteral obstruction N13.5\nN13.5 Kinking and stricture of ureter without hydronephrosis',
    'E10.9': 'Diabetes\n- type 1\n-- without complications E10.9\nE10.9 Type 1 diabetes mellitus without complications',
    'E11.0': 'Diabetes\n- type 2\n-- with coma E11.0\nE11.0 Type 2 diabetes mellitus with coma',
    'E11.1': 'Diabetes\n- type 2\n-- with ketoacidosis E11.1\nE11.1 Type 2 diabetes mellitus with ketoacidosis',
    'E11.6': 'Diabetes\n- type 2\n-- with other specified complications E11.6\nE11.6 Type 2 diabetes mellitus with other specified complications',
    'E11.7': 'Diabetes\n- type 2\n-- with multiple complications E11.7\nE11.7 Type 2 diabetes mellitus with multiple complications',
    'E14.9': 'Diabetes\n- unspecified\n-- without complications E14.9\nE14.9 Unspecified diabetes mellitus without complications',
    'E05.0': 'Hyperthyroidism\n- with diffuse goitre E05.0\nE05.0 Thyrotoxicosis with diffuse goitre',
    'E05.9': 'Hyperthyroidism\n- unspecified E05.9\nE05.9 Thyrotoxicosis, unspecified',
    'E03.9': 'Hypothyroidism\n- unspecified E03.9\nE03.9 Hypothyroidism, unspecified',
    'E27.1': 'Insufficiency\n- adrenocortical\n-- primary E27.1\nE27.1 Primary adrenocortical insufficiency',
    'E24.0': 'Syndrome\n- Cushing\n-- pituitary-dependent E24.0\nE24.0 Pituitary-dependent Cushing disease',
    'E16.0': 'Hypoglycaemia\n- with coma E16.0\nE16.0 Drug-induced hypoglycaemia without coma',
    'E87.0': 'Hypernatraemia\n- E87.0\nE87.0 Hyperosmolality and hypernatraemia',
    'E87.1': 'Hyponatraemia\n- E87.1\nE87.1 Hyponatraemia',
    'E87.5': 'Hyperkalaemia\n- E87.5\nE87.5 Hyperkalaemia',
    'E87.6': 'Hypokalaemia\n- E87.6\nE87.6 Hypokalaemia',
    'O10.0': 'Hypertension\n- pre-existing\n-- essential\n--- complicating pregnancy O10.0\nO10.0 Pre-existing essential hypertension complicating pregnancy, childbirth and the puerperium',
    'O13': 'Hypertension\n- gestational\n-- without significant proteinuria O13\nO13 Gestational hypertension without significant proteinuria',
    'O14.0': 'Pre-eclampsia\n- mild O14.0\nO14.0 Mild to moderate pre-eclampsia',
    'O14.1': 'Pre-eclampsia\n- severe O14.1\nO14.1 Severe pre-eclampsia',
    'O15.0': 'Eclampsia\n- in pregnancy O15.0\nO15.0 Eclampsia in pregnancy',
    'O15.9': 'Eclampsia\n- unspecified O15.9\nO15.9 Eclampsia, unspecified as to time period',
    'O20.0': 'Abortion\n- threatened O20.0\nO20.0 Threatened abortion',
    'O21.0': 'Vomiting\n- pregnancy\n-- mild O21.0\nO21.0 Mild hyperemesis gravidarum',
    'O21.1': 'Vomiting\n- pregnancy\n-- hyperemesis with metabolic disturbance O21.1\nO21.1 Hyperemesis gravidarum with metabolic disturbance',
    'O00.0': 'Pregnancy\n- ectopic\n-- abdominal O00.0\nO00.0 Abdominal pregnancy',
    'O00.9': 'Pregnancy\n- ectopic\n-- unspecified O00.9\nO00.9 Ectopic pregnancy, unspecified',
    'O08.1': 'Haemorrhage\n- following\n-- abortion O08.1\nO08.1 Delayed or excessive haemorrhage following abortion and ectopic and molar pregnancy',
    'O08.9': 'Complications\n- following\n-- abortion\n--- unspecified O08.9\nO08.9 Unspecified complication following abortion and ectopic and molar pregnancy',
    'O42.0': 'Rupture\n- membranes\n-- premature\n--- labour within 24 hours O42.0\nO42.0 Premature rupture of membranes, onset of labour within 24 hours',
    'O42.9': 'Rupture\n- membranes\n-- premature\n--- unspecified O42.9\nO42.9 Premature rupture of membranes, unspecified',
    'O72.1': 'Haemorrhage\n- postpartum\n-- other immediate O72.1\nO72.1 Other immediate postpartum haemorrhage',
    'Z37.1': 'Outcome\n- delivery\n-- single\n--- stillborn Z37.1\nZ37.1 Single stillbirth',
    'Z37.2': 'Outcome\n- delivery\n-- twins\n--- both liveborn Z37.2\nZ37.2 Twins, both liveborn',
    'Z37.4': 'Outcome\n- delivery\n-- twins\n--- both stillborn Z37.4\nZ37.4 Twins, both stillborn',
    'S02.0': 'Fracture\n- skull\n-- vault S02.0\nS02.0 Fracture of vault of skull',
    'S06.3': 'Injury\n- intracranial\n-- focal S06.3\nS06.3 Focal brain injury',
    'S22.0': 'Fracture\n- vertebra\n-- thoracic S22.0\nS22.0 Fracture of thoracic vertebra',
    'S32.0': 'Fracture\n- vertebra\n-- lumbar S32.0\nS32.0 Fracture of lumbar vertebra',
    'S42.2': 'Fracture\n- humerus\n-- upper end S42.2\nS42.2 Fracture of upper end of humerus',
    'S42.3': 'Fracture\n- humerus\n-- shaft S42.3\nS42.3 Fracture of shaft of humerus',
    'S52.2': 'Fracture\n- radius\n-- shaft S52.2\nS52.2 Fracture of shaft of radius',
    'S52.5': 'Fracture\n- radius\n-- lower end S52.5\nS52.5 Fracture of lower end of radius',
    'S62.3': 'Fracture\n- metacarpal S62.3\nS62.3 Fracture of other metacarpal bone',
    'S82.1': 'Fracture\n- tibia\n-- upper end S82.1\nS82.1 Fracture of upper end of tibia',
    'S82.2': 'Fracture\n- tibia\n-- shaft S82.2\nS82.2 Fracture of shaft of tibia',
    'S82.6': 'Fracture\n- fibula\n-- lateral malleolus S82.6\nS82.6 Fracture of lateral malleolus',
    'S92.0': 'Fracture\n- calcaneus S92.0\nS92.0 Fracture of calcaneus',
    'M16.1': 'Osteoarthritis\n- hip\n-- primary M16.1\nM16.1 Primary osteoarthritis, hip',
    'M17.1': 'Osteoarthritis\n- knee\n-- primary M17.1\nM17.1 Primary osteoarthritis, knee',
    'M54.5': 'Pain\n- low back M54.5\nM54.5 Low back pain',
    'M54.4': 'Lumbago\n- with sciatica M54.4\nM54.4 Lumbago with sciatica',
    '54.11': 'Laparotomy\n- exploratory 54.11\n54.11 Exploratory laparotomy',
    '54.19': 'Laparotomy\n- other 54.19\n54.19 Other laparotomy',
    '46.10': 'Colostomy\n- temporary 46.10\n46.10 Colostomy, not otherwise specified',
    '46.13': 'Colostomy\n- permanent 46.13\n46.13 Permanent colostomy',
    '45.73': 'Resection\n- bowel\n-- right hemicolectomy 45.73\n45.73 Right hemicolectomy',
    '45.75': 'Resection\n- bowel\n-- left hemicolectomy 45.75\n45.75 Left hemicolectomy',
    '51.22': 'Cholecystectomy\n- laparoscopic 51.22\n51.22 Laparoscopic cholecystectomy',
    '51.23': 'Cholecystectomy\n- other 51.23\n51.23 Other cholecystectomy',
    '52.7': 'Pancreatectomy\n- total 52.7\n52.7 Radical pancreaticoduodenectomy',
    '53.00': 'Repair\n- hernia\n-- inguinal\n--- unilateral 53.00\n53.00 Unilateral repair of inguinal hernia, not otherwise specified',
    '53.05': 'Repair\n- hernia\n-- inguinal\n--- laparoscopic 53.05\n53.05 Repair of inguinal hernia, laparoscopic approach',
    '57.6': 'Cystectomy\n- total 57.6\n57.6 Total cystectomy',
    '60.5': 'Prostatectomy\n- transurethral 60.5\n60.5 Transurethral prostatectomy',
    '60.29': 'Prostatectomy\n- other 60.29\n60.29 Other transurethral prostatectomy',
    '77.35': 'Division\n- bone\n-- femur 77.35\n77.35 Other division of bone, femur',
    '81.54': 'Replacement\n- hip\n-- total 81.54\n81.54 Total hip replacement',
    '81.55': 'Replacement\n- knee\n-- total 81.55\n81.55 Total knee replacement',
    '87.03': 'Tomography\n- computerized axial\n-- head 87.03\n87.03 Computerized axial tomography of head',
    '87.41': 'Tomography\n- computerized axial\n-- thorax 87.41\n87.41 Computerized axial tomography of thorax',
    '88.01': 'Tomography\n- computerized axial\n-- abdomen 88.01\n88.01 Computerized axial tomography of abdomen',
    '88.38': 'Tomography\n- computerized axial\n-- lumbar spine 88.38\n88.38 Computerized axial tomography of lumbar spine',
    '88.91': 'Imaging\n- magnetic resonance\n-- brain 88.91\n88.91 Magnetic resonance imaging of brain',
    '88.92': 'Imaging\n- magnetic resonance\n-- chest 88.92\n88.92 Magnetic resonance imaging of chest',
    '88.93': 'Imaging\n- magnetic resonance\n-- spinal canal 88.93\n88.93 Magnetic resonance imaging of spinal canal',
    '88.94': 'Imaging\n- magnetic resonance\n-- musculoskeletal 88.94\n88.94 Magnetic resonance imaging of musculoskeletal',
    '44.13': 'Gastroscopy\n- other 44.13\n44.13 Other gastroscopy',
    '45.13': 'Endoscopy\n- large intestine\n-- colonoscopy 45.13\n45.13 Colonoscopy',
    '45.23': 'Endoscopy\n- small bowel 45.23\n45.23 Other endoscopy of small intestine',
    '52.14': 'ERCP\n- pancreatography 52.14\n52.14 Endoscopic retrograde pancreatography',
    '51.11': 'Cholangiography\n- endoscopic retrograde 51.11\n51.11 Endoscopic retrograde cholangiography',
    '37.21': 'Catheterization\n- heart\n-- right 37.21\n37.21 Right heart cardiac catheterization',
    '37.22': 'Catheterization\n- heart\n-- left 37.22\n37.22 Left heart cardiac catheterization',
    '87.62': 'Angiography\n- coronary 87.62\n87.62 Other heart angiography',
    '89.14': 'Electroencephalogram\n- EEG 89.14\n89.14 Electroencephalogram',
    '89.37': 'Spirometry\n- 89.37\n89.37 Vital capacity determination',
    '92.18': 'Scan\n- bone 92.18\n92.18 Other bone scan',
    'I21.1': 'Infarction\n- myocardial\n-- acute\n--- inferior I21.1\nI21.1 Acute transmural myocardial infarction of inferior wall',
    'I21.0': 'Infarction\n- myocardial\n-- acute\n--- anterior I21.0\nI21.0 Acute transmural myocardial infarction of anterior wall',
    'I21.9': 'Infarction\n- myocardial\n-- acute I21.9\nI21.9 Acute myocardial infarction, unspecified',
    'I21.4': 'Infarction\n- myocardial\n-- acute\n--- subendocardial I21.4\nI21.4 Acute subendocardial myocardial infarction',
    'I63.9': 'Infarction\n- cerebral I63.9\nI63.9 Cerebral infarction, unspecified',
    'I61.9': 'Haemorrhage\n- intracranial I61.9\nI61.9 Nontraumatic intracranial haemorrhage, unspecified',
    'I10':   'Hypertension\n- essential I10\nI10 Essential (primary) hypertension',
    'E11.9': 'Diabetes\n- type 2 E11.9\nE11.9 Type 2 diabetes mellitus without complications',
    'E11.3': 'Diabetes\n- type 2\n-- with\n--- ophthalmic complication E11.3\nE11.3 Type 2 diabetes mellitus with ophthalmic complications',
    'E11.2': 'Diabetes\n- type 2\n-- with\n--- renal complication E11.2\nE11.2 Type 2 diabetes mellitus with renal complications',
    'E11.4': 'Diabetes\n- type 2\n-- with\n--- neurological complication E11.4\nE11.4 Type 2 diabetes mellitus with neurological complications',
    'E11.5': 'Diabetes\n- type 2\n-- with\n--- peripheral circulatory complication E11.5\nE11.5 Type 2 diabetes mellitus with peripheral circulatory complications',
    'H36.0': 'Retinopathy\n- diabetic H36.0\nH36.0 Diabetic retinopathy',
    'J13':   'Pneumonia\n- due to\n-- Streptococcus pneumoniae J13\nJ13 Pneumonia due to Streptococcus pneumoniae',
    'J14':   'Pneumonia\n- due to\n-- Haemophilus influenzae J14\nJ14 Pneumonia due to Haemophilus influenzae',
    'J15.0': 'Pneumonia\n- due to\n-- Klebsiella pneumoniae J15.0\nJ15.0 Pneumonia due to Klebsiella pneumoniae',
    'J15.2': 'Pneumonia\n- due to\n-- Staphylococcus J15.2\nJ15.2 Pneumonia due to staphylococcus',
    'J18.1': 'Pneumonia\n- lobar J18.1\nJ18.1 Lobar pneumonia, unspecified',
    'J18.9': 'Pneumonia\n- unspecified J18.9\nJ18.9 Pneumonia, unspecified',
    'J44.0': 'Disease\n- pulmonary\n-- chronic obstructive\n--- with acute lower respiratory infection J44.0\nJ44.0 Chronic obstructive pulmonary disease with acute lower respiratory infection',
    'J44.1': 'Disease\n- pulmonary\n-- chronic obstructive\n--- with acute exacerbation J44.1\nJ44.1 Chronic obstructive pulmonary disease with acute exacerbation',
    'J44.9': 'Disease\n- pulmonary\n-- chronic obstructive\n--- unspecified J44.9\nJ44.9 Chronic obstructive pulmonary disease, unspecified',
    'K35.2': 'Appendicitis\n- acute\n-- with peritonitis K35.2\nK35.2 Acute appendicitis with generalized peritonitis',
    'K35.3': 'Appendicitis\n- acute\n-- with peritoneal abscess K35.3\nK35.3 Acute appendicitis with peritoneal abscess',
    'K35.8': 'Appendicitis\n- acute\n-- without mention of peritonitis K35.8\nK35.8 Other and unspecified acute appendicitis',
    'K36':   'Appendicitis\n- other K36\nK36 Other appendicitis',
    'K37':   'Appendicitis\n- unspecified K37\nK37 Unspecified appendicitis',
    '47.01': 'Appendectomy\n- laparoscopic 47.01\n47.01 Laparoscopic appendectomy',
    '47.09': 'Appendectomy\n- other 47.09\n47.09 Other appendectomy',
    '47.2':  'Drainage\n- appendiceal abscess 47.2\n47.2 Drainage of appendiceal abscess',
    'J96.0': 'Failure\n- respiratory\n-- acute J96.0\nJ96.0 Acute respiratory failure',
    'J96.1': 'Failure\n- respiratory\n-- chronic J96.1\nJ96.1 Chronic respiratory failure',
    'J96.1': 'Failure\n- respiratory\n-- chronic J96.1\nJ96.1 Chronic respiratory failure',
    'B95.3': 'Streptococcus\n- pneumoniae\n-- as cause of disease classified elsewhere B95.3\nB95.3 Streptococcus pneumoniae as the cause of diseases classified elsewhere',
    'B96.1': 'Klebsiella\n- pneumoniae\n-- as cause of disease classified elsewhere B96.1\nB96.1 Klebsiella pneumoniae as the cause of diseases classified elsewhere',
    'B96.2': 'Escherichia\n- coli\n-- as cause of disease classified elsewhere B96.2\nB96.2 Escherichia coli as the cause of diseases classified elsewhere',
    '87.44': 'X-ray\n- chest\n-- routine 87.44\n87.44 Routine chest x-ray',
    '87.49': 'X-ray\n- chest\n-- other 87.49\n87.49 Other x-ray of chest',
    '87.03': 'Scan\n- CT\n-- head 87.03\n87.03 Computerized axial tomography of head',
    '87.41': 'Scan\n- CT\n-- thorax 87.41\n87.41 Computerized axial tomography of thorax',
    '88.01': 'Scan\n- CT\n-- abdomen 88.01\n88.01 Computerized axial tomography of abdomen',
    '88.91': 'Imaging\n- magnetic resonance\n-- brain 88.91\n88.91 Magnetic resonance imaging of brain',
    '88.76': 'Ultrasonography\n- abdominal 88.76\n88.76 Abdominal ultrasonography',
    '88.78': 'Ultrasonography\n- gravid uterus 88.78\n88.78 Diagnostic ultrasound of gravid uterus',
    '88.72': 'Echocardiography\n- cardiac 88.72\n88.72 Diagnostic ultrasound of heart',
    '89.52': 'Electrocardiogram\n- routine ECG 89.52\n89.52 Electrocardiogram',
    '89.65': 'Measurement\n- arterial blood gases 89.65\n89.65 Measurement of arterial blood gases',
    '93.94': 'Therapy\n- nebulizer 93.94\n93.94 Respiratory medication administered by nebulizer',
    '93.96': 'Oxygenation\n- other oxygen enrichment 93.96\n93.96 Other oxygen enrichment',
    '33.22': 'Bronchoscopy\n- diagnostic 33.22\n33.22 Fiber-optic bronchoscopy',
    '33.23': 'Bronchoscopy\n- therapeutic 33.23\n33.23 Other bronchoscopy',
    '93.96': 'Oxygenation\n- supplemental oxygen 93.96\n93.96 Other oxygen enrichment',
    '93.91': 'Breathing\n- intermittent positive pressure (IPPB) 93.91\n93.91 Intermittent positive pressure breathing',
    '96.04': 'Intubation\n- endotracheal 96.04\n96.04 Insertion of endotracheal tube',
    '96.70': 'Ventilation\n- mechanical\n-- continuous 96.70\n96.70 Continuous invasive mechanical ventilation',
    '90.59': 'Examination\n- blood\n-- chemical 90.59\n90.59 Other blood chemistry',
    '90.41': 'Examination\n- sputum\n-- culture 90.41\n90.41 Bacteriological examination of sputum',
    '90.54': 'Examination\n- blood\n-- culture 90.54\n90.54 Blood culture',
    '91.31': 'Examination\n- urine\n-- routine 91.31\n91.31 Urinalysis',
    '91.49': 'Examination\n- histological\n-- other 91.49\n91.49 Other histological examination',
    'H25.1': 'Cataract\n- senile\n-- nuclear H25.1\nH25.1 Senile nuclear cataract',
    'H25.2': 'Cataract\n- senile\n-- morgagnian H25.2\nH25.2 Morgagnian cataract',
    'H25.9': 'Cataract\n- senile\n-- unspecified H25.9\nH25.9 Senile cataract, unspecified',
    'H26.0': 'Cataract\n- infantile\n-- and juvenile H26.0\nH26.0 Infantile and juvenile cataract',
    'H26.1': 'Cataract\n- senile\n-- immature H26.1\nH26.1 Cataract, senile, immature',
    'H26.9': 'Cataract\n- unspecified H26.9\nH26.9 Cataract, unspecified',
    '13.41': 'Extraction\n- lens\n-- phacoemulsification\n--- without IOL 13.41\n13.41 Phacoemulsification and aspiration of cataract',
    '13.71': 'Extraction\n- lens\n-- extracapsular\n--- by temporal inferior route 13.71\n13.71 Extracapsular extraction of lens by temporal inferior route',
    '13.72': 'Extraction\n- lens\n-- phacoemulsification\n--- with insertion of intraocular lens prosthesis 13.72\n13.72 Phacoemulsification and insertion of intraocular lens prosthesis',
};
