const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),ctx=vm.createContext({Response,URL,AbortSignal,console});
require('./load-coding.cjs')(ctx,root);
(async()=>{
 const diagnosis={code:'E11.9',lead_term:'Diabetes mellitus type 2',who_validation:{valid:true}};
 const lookup=async()=>({valid:true,results:[{code:'E11.9',index_terms:['Diabetes - type 2','Diabetes - non-insulin-dependent']},{code:'E10.9',index_terms:['Diabetes - type 1']}]});
 let r=await ctx.resolveWHOIndexReferences(diagnosis,{},lookup);
 assert.equal(r.status,'unverified');assert.equal(r.index_paths.length,2);assert.equal(r.index_path,undefined);
 assert.ok(r.index_paths.every(p=>p.code==='E11.9'));
 r=await ctx.resolveWHOIndexReferences({...diagnosis,clinical_validation:{status:'review_required'}},{},lookup);
 assert.equal(r.index_paths.length,2);assert.equal(r.status,'unverified');
 r=await ctx.resolveWHOIndexReferences(diagnosis,{},async()=>({valid:true,results:[{code:'E11.9',index_terms:[]}]}));
 assert.equal(r.index_paths,undefined,'never synthesize index path from diagnosis or title');
 const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
 vm.runInContext(fs.readFileSync(path.join(root,'known-paths.js'),'utf8'),vm.createContext({window:{}}));
 const ui=vm.createContext({window:{KNOWN_PATHS:{}},currentLang:'id',isIMCode:()=>false,renderLeadPath:p=>p,renderVol1Notes:()=>'',renderWHOGuidance:()=>'',renderValidations:()=>''});
 vm.runInContext(html.slice(html.indexOf('function escapeHTML('),html.indexOf('function escapeHTML(')+html.slice(html.indexOf('function escapeHTML(')).indexOf('\n}'))+'\n}',ui);
 vm.runInContext(html.slice(html.indexOf('function renderWHOIndexPath('),html.indexOf('function renderWHOGuidance(')),ui);
 vm.runInContext(html.slice(html.indexOf('function conciseResultText('),html.indexOf('function renderResults(')),ui);
 const index=await ctx.resolveWHOIndexReferences(diagnosis,{},lookup);
 let output=ui.renderResultCard({...diagnosis,role:'DU',who_index:index},{procedure:false,primary:true,warnings:[],duReason:''});
 assert.match(output,/index-reference" open/);assert.match(output,/Kandidat jalur 2/);assert.match(output,/- type 2/);assert.match(output,/Belum terverifikasi/);
 assert.ok(output.indexOf('Kandidat jalur')<output.indexOf('Dasar coding'));
 output=ui.renderWHOIndexPath({code:'E11.91',scope:'parent_reference_only',who_anchor_code:'E11.9',parent_index:index,parent_entries:[{code:'E11.9',description:'parent'}]});
 assert.match(output,/Kandidat jalur 2/);assert.match(output,/tidak memvalidasi kode anak/);
 output=ui.renderWHOIndexPath({code:'E11.9',status:'unverified',index_paths:[{code:'E11.9',lead_term:'<script>alert(1)</script>',modifiers:[]}]});
 assert.ok(!output.includes('<script>'));assert.match(output,/&lt;script&gt;/);
 console.log('PASS: source candidates retained independently of verification, exact code, IM parent, visible path and escaped source');
})().catch(e=>{console.error(e);process.exitCode=1});
