const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),ctx=vm.createContext({Response,URL,AbortSignal,console});require('./load-coding.cjs')(ctx,root);
const input='Diagnosis utama dan riwayat : G2P1A0 hamil 7 bulan, diketahui fetus ke 2 dengan kista rahim\nHb : 9,1\nDiagnosis : P2 A0 partus prematurus 32-33 minggu dengan SC ai gemelli anak ke 2 + TTTS + IUFD + bekas SC + kista ovarium bilateral';
const model=()=>({diagnoses:[{code:'O60.1',role:'DU',documentation_quote:'partus prematurus 32-33 minggu',reasoning:'pertama ditulis'},{code:'O73.2',role:'DS',description:'TTTS',documentation_quote:'TTTS',dagger_asterisk:'dagger'}],procedures:[],du_reasoning:'Pertama ditulis',ics_context:{mb_rule:'MB5',mb5_mode:'alternative_diagnoses',mb_trigger_quote:input.split('\n').at(-1),documented_du_quote:input.split('\n').at(-1)}});
let p=ctx.normalizeModelResult(model());ctx.auditClinicalCoding(p,input);
assert.equal(p.diagnoses[1].code,'O43.0');assert.equal(p.diagnoses[1].dagger_asterisk,null);assert.equal(p.diagnoses[0].role,'DU','do not force TTTS into DU');assert.equal(p.primary_decision.status,'clarification_required');assert.equal(p.ics_context.mb_rule,null);assert.equal(p.ics_context.documented_du_quote,null);assert.ok(!p.du_reasoning.includes('Pertama ditulis'));assert.equal(p.procedures.length,0,'audit does not invent procedures from diagnosis list');assert.ok(p.diagnoses.every(d=>!/^O99|^D50|^Z37/.test(d.code)),'do not infer anemia or birth outcome');
ctx.auditClinicalCoding(p,input);assert.equal(p.diagnoses.filter(d=>d.code==='O43.0').length,1);
for(const text of [input.replace(' + TTTS',' + Suspek TTTS'),input.replace(' + TTTS',' + Tidak ada TTTS'),'Pasien bayi. Rekam bayi: Diagnosis: TTTS. Ibu hamil.', 'Riwayat: hamil dengan TTTS.']) {
 p=ctx.normalizeModelResult(model());ctx.auditClinicalCoding(p,text);assert.equal(p.diagnoses[1].code,'O73.2',text);assert.equal(p.primary_decision,undefined);
}
p=ctx.normalizeModelResult({diagnoses:[{code:'O43.0',role:'DU',documentation_quote:'TTTS'}],procedures:[]});ctx.auditClinicalCoding(p,input+'\nDiagnosis utama: TTTS');assert.equal(p.primary_decision.status,'documented_requires_review');
p=ctx.normalizeModelResult({diagnoses:[{code:'O60.1',role:'DU',documentation_quote:'partus prematurus'}]});ctx.auditClinicalCoding(p,input);assert.ok(p.diagnoses.some(d=>d.code==='O43.0'),'recover omitted documented maternal TTTS');
p=ctx.normalizeModelResult(model());ctx.auditClinicalCoding(p,input+'\nDiagnosis utama: TTTS');assert.equal(p.diagnoses[1].role,'DU');assert.equal(p.diagnoses[0].role,'DS');
const prompt=ctx.buildPrompt(input,'Bahasa Indonesia');assert.ok(prompt.includes('bukan diagnosis alternatif MB5'));assert.ok(prompt.includes('74.99'));assert.ok(prompt.includes('O31.2 membutuhkan continuing pregnancy'));
(async()=>{const queries=[];const db={prepare:sql=>({bind:(...params)=>({all:async()=>{queries.push({sql,params});return {results:sql.includes('tabular_entries')?[{code:params[0],title:'Source',raw_text:'Source',pdf_page:632}]:[]};}})})};const refs=await ctx.retrievePDFContext(db,input);assert.ok(refs.some(r=>r.code==='O43.0'));assert.ok(refs.some(r=>r.code==='O31.2'));assert.ok(refs.every(r=>r.review_status==='extracted_requires_review'));assert.ok(queries.length<=14);console.log('PASS: maternal TTTS mapping, coexistence versus MB5, provisional DU, no inference from Hb or delivery outcome, source retrieval, repeat and negation safety');})().catch(e=>{console.error(e);process.exitCode=1});
// Exercise the actual UI grouping and clarification output, without a browser dependency.
const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),nodes={};
const ui=vm.createContext({currentLang:'id',document:{getElementById:id=>nodes[id]||(nodes[id]={style:{},value:input}),querySelector:()=>({addEventListener(){}})},escapeHTML:s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),renderResultCard:(d,o)=>`<article>${d.role}:${d.code}:${o.primary}</article>`,renderValidations:()=>''});
vm.runInContext(html.slice(html.indexOf('function renderResults(result)'),html.indexOf('</script>',html.indexOf('function renderResults(result)'))),ui);
const ambiguous=ctx.normalizeModelResult(model());ctx.auditClinicalCoding(ambiguous,input);ui.renderResults(ambiguous);assert.equal(nodes.diagCount.textContent,'1 DU · 1 DS');assert.ok(nodes.diagList.innerHTML.includes('DU masih usulan'));assert.ok(nodes.resultStatus.innerHTML.includes('DU perlu klarifikasi'));assert.ok(nodes.diagList.innerHTML.indexOf('DU:O60.1')<nodes.diagList.innerHTML.indexOf('DS:O43.0'));

let followup=ctx.normalizeModelResult({diagnoses:[{code:'O60.3',role:'DU',documentation_quote:'partus prematurus 32-33 minggu dengan SC ai gemelli'},{code:'O43.0',role:'DS',documentation_quote:'TTTS'}],procedures:[{code:'74.0',documentation_quote:'SC ai gemelli'}]});ctx.auditClinicalCoding(followup,input);assert.equal(followup.diagnoses[0].code,'O60.1');assert.equal(followup.procedures[0].code,'74.99');
followup=ctx.normalizeModelResult({diagnoses:[{code:'O60.3',role:'DU',documentation_quote:'partus prematurus 32-33 minggu dengan SC ai gemelli'}],procedures:[{code:'74.0',documentation_quote:'SC klasik'}]});ctx.auditClinicalCoding(followup,input+'\nTindakan: SC klasik. Persalinan tanpa persalinan spontan.');assert.equal(followup.diagnoses[0].code,'O60.3');assert.equal(followup.procedures[0].code,'74.0');
